Various CISA tests has been fixed
maester365/maester pull request #190
Opened 2024-05-23 18:01 UTC by tdcthosc

The following tests has been hotfixed by changing -All to -Active until a bug regarding read-only permissions for roleEligibilityScheduleRequests is fixed. See: https://learn.microsoft.com/en-us/answers/questions/1656176/unable-to-get-rolemanagement-directory-roleeligibi
* Test-MtCisaCloudGlobalAdmin.ps1
* Test-MtCisaGlobalAdminCount.ps1
* Test-MtCisaGlobalAdminRatio.ps1

Test-MtCisaPermanentRoleAssignment.ps1 also fails due to above bug. This has been fixed by adding API permission "RoleManagement.Read.All" to Microsoft Graph scopes.

A divide by zero condition in Test-MtCisaGlobalAdminRatio.ps1 has been fixed. This occurs if no users exists in any other privileged assignments outside Global Administrators.

An output mistake in the following tests has been fixed.
* Test-MtCisaAppUserConsent.ps1
* Test-MtCisaCloudGlobalAdmin.ps1
* Test-MtCisaUnmanagedRoleAssignment.ps1

Test-MtCisaAppRegistration.Tests.ps1 used the wrong function to test with.

Skip conditions has been moved to Describe statement instead for the following tests, otherwise it would produce undesired markdown descriptions from Test-MtCisaPhishResistant.
* Test-MtCisaAuthenticatorContext.Tests.ps1
* Test-MtCisaMfa.Tests.ps1

Adjusted scopes in Get-MtGraphScope
* 'RoleManagement.Read.All' has been added.
* 'Policy.Read.ConditionalAccess' has been removed. It should not be required when 'Policy.Read.All' is already part of the scopes.
* '/maester/website/docs/sections/permissions.md' has been updated accordingly.

2024-05-28 08:45 UTC, merill commented
Thanks a lot for the fixes @tdcthosc awesome work.

I'm tagging @Snozzberries for a quick review as the original author of these tests.

2024-05-29 01:00 UTC, Snozzberries requested changes
A few tweaks, but good additions. Thank you @tdcthosc

2024-05-29 01:00 UTC, soulemike commented on powershell/public/CISA/Entra/Test-MtCisaCloudGlobalAdmin.ps1
What are your thoughts on adding something like `Write-Warning "Current test only captures active role assignments. Ref https://github.com/maester365/maester/issues/195"`?

2024-05-29 01:00 UTC, soulemike commented on powershell/public/CISA/Entra/Test-MtCisaGlobalAdminCount.ps1
Same for _all_ to _active_

2024-05-29 01:00 UTC, soulemike commented on powershell/public/CISA/Entra/Test-MtCisaGlobalAdminRatio.ps1
Same for _all_ to _active_

2024-05-31 07:53 UTC, tdcthosc commented on powershell/public/CISA/Entra/Test-MtCisaCloudGlobalAdmin.ps1
I think we should add it in the markdown result instead to avoid cluttering the console output.

2024-05-31 13:11 UTC, Snozzberries commented on powershell/public/CISA/Entra/Test-MtCisaCloudGlobalAdmin.ps1
Makes sense to me. Feel comfortable adding that to the MD?

2024-06-01 16:14 UTC, Snozzberries commented on powershell/public/Get-MtGraphScope.ps1
We will need to keep `Policy.Read.ConditionalAccess` as well based on https://github.com/maester365/maester/pull/199#issuecomment-2143395506

2024-06-03 06:30 UTC, tdcthosc commented on powershell/public/CISA/Entra/Test-MtCisaCloudGlobalAdmin.ps1
Sure – I have added it now. Looks alright to you?

2024-06-03 13:54 UTC, Snozzberries commented
Looks good to me. @merill for merge review.

2024-06-15 22:27 UTC, merill approved these changes
Nice work folks. I added more info on the error messages and included links to the admin center.

2024-06-15 22:29 UTC, merged