#5: Send report as Teams channel message
maester365/maester pull request #300
Opened 2024-07-04 18:53 UTC by GuidoBaijense

Had some fun and learned something new. This PR adds functionality to send Microsoft Teams Channel Messages with the Maester-report summary as described in issue #5 . I used Send-MtMail.ps1 as reference and tried to update all documentation. 

>Note: Following MS Teams Terms of Use, it is not allowed to use Teams as a logging system. Only messages that will be read are allowed. Also, there is no official support for sending teams messages with application permissions. However, this might be possible with the migration permissions. 

Next might be a switch to send the message to a user instead of a teams channel. I think that it's better to spend my time on something more useful :).

Since I didn't want to create a new release, I haven't updated the Maester.psd1 with new guids or version numbers.

2024-07-05 07:54 UTC, merill requested changes
This is really cool. Thanks a lot. I've made a few suggestions. Would you be able to resubmit with the changes?

Tx!

2024-07-05 07:54 UTC, merill commented on powershell/public/Invoke-Maester.ps1
> +        [string[]] $TeamId,
Does this need to be a string array?

2024-07-05 07:54 UTC, merill commented on powershell/public/Invoke-Maester.ps1
> +        [string[]] $ChannelId,
Same here for string array. Shouldn't it be a [string] like the other parameters?

2024-07-05 07:54 UTC, merill commented on powershell/public/Invoke-Maester.ps1
> +        [string[]] $ChannelId,
Let's call this TeamChanelId so we know it's related to the other Teams property.

2024-07-05 07:54 UTC, merill commented on powershell/public/Get-MtGraphScope.ps1
> +        [switch] $SendChannelMessage,
Let's call this SendTeamsMessage to make it clear. Not many folks would understand Channel.

2024-07-05 07:54 UTC, merill commented on powershell/public/Send-MtTeamsChannelMessage.ps1
> +                tenantName    = $MaesterResults.TenantName
Can we keep the variable name case uniform? Some start with lowercase (e.g. moduleVersion) and others start with upper case (e.g. NotRunCount).

2024-07-05 10:15 UTC, GuidoBaijense commented
> This is really cool. Thanks a lot. I've made a few suggestions. Would you be able to resubmit with the changes?
> 
> Tx!

Good review! Thank you. I resolved all of your comments. (as far as I can see)

2024-07-06 07:38 UTC, merill approved these changes
Excellent!

2024-07-06 07:38 UTC, merged