Additional clarity of permissions for Azure and EXO with App Regs and…
maester365/maester pull request #378
Opened 2024-07-22 03:49 UTC by Snozzberries

… new addition summarizing Container App Jobs

2024-07-23 23:52 UTC, merill requested changes
@Snozzberries this is a good docs update. 

In create-entra-app.md should be mention why they are optional (ie call out they are required for running the CISA tests)?

2024-07-24 00:27 UTC, Snozzberries commented
> @Snozzberries this is a good docs update.
> 
> In create-entra-app.md should be mention why they are optional (ie call out they are required for running the CISA tests)?

Good thought, updated.

2024-07-31 04:12 UTC, merill approved these changes

2024-07-31 04:12 UTC, merill commented
Nice. Tx!

2024-07-31 04:12 UTC, merged